[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --legacy-peer-deps']

[phases.build]
cmds = ['bash build.sh']

[start]
cmd = 'HOSTNAME=0.0.0.0 node .next/standalone/server.js'
